FROM python:3.9-slim

WORKDIR /app

# Install curl + docker CLI (IMPORTANT FIX)
RUN apt-get update && apt-get install -y \
    curl \
    docker.io \
    && apt-get clean

COPY . .

RUN pip install flask requests

CMD ["python", "healer.py"]