

services:
  app:
    build: ./app
    container_name: self_healing_app
    ports:
      - "5000:5000"
    restart: "no"
    volumes:
      - ./logs:/logs 
    environment:
      - PYTHONUNBUFFERED=1

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./monitoring/alert_rules.yml:/etc/prometheus/alert_rules.yml
    ports:
      - "9090:9090"

  alertmanager:
    image: prom/alertmanager
    container_name: alertmanager
    volumes:
      - ./alerting/alertmanager.yml:/etc/alertmanager/alertmanager.yml
    ports:
      - "9093:9093"
  
  healer:
    build: ./automation
    container_name: healer
    command: ["python", "healer.py"]  
    ports:
      - "5001:5001"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock 
    environment:
      - PYTHONUNBUFFERED=1  

  log_analyzer:
    build:
      context: ./automation
      dockerfile: dockerfile.log
    container_name: log_analyzer
    command: ["python", "log_analyzer.py"]
    volumes:
      - ./logs:/logs
    environment:
      - PYTHONUNBUFFERED=1

  ai_agent:
    build: ./automation
    container_name: ai_agent
    command: ["python", "ai_agent.py"]
    volumes:
      - ./logs:/logs
      - ./shared:/shared   
    environment:
      - PYTHONUNBUFFERED=1  
    extra_hosts:
      - "host.docker.internal:172.17.0.1"

  anomaly_detector:
    build: ./automation   
    container_name: anomaly_detector
    command: ["python", "anomaly_detector.py"]
    depends_on:
      - prometheus
    volumes:
      - ./logs:/logs
      - ./shared:/shared
      - ./automation:/app
    environment:
      - PYTHONUNBUFFERED=1