sonar.projectKey= nirmalyavishal96-hash_self-healing-devops-agent
sonar.organization= nirmalyavishal96-hash
sonar.sources=services
sonar.python.version=3.10
sonar.projectName=self-healing-devops-agent
sonar.sourceEncoding=UTF-8