apiVersion: apps/v1
kind: Deployment
metadata:
  name: decision-engine
spec:
  replicas: 1
  selector:
    matchLabels:
      app: decision-engine
  template:
    metadata:
      labels:
        app: decision-engine
    spec:
      containers:
        - name: decision-engine
          image: decision_engine:latest
          imagePullPolicy: Never