apiVersion: apps/v1
kind: Deployment
metadata:
  name: healer-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: healer-service
  template:
    metadata:
      labels:
        app: healer-service
    spec:
      serviceAccountName: healer-sa
      containers:
        - name: healer-service
          image: healer_service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 5001