apiVersion: v1
kind: ServiceAccount
metadata:
  name: healer-sa

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: healer-role
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "delete"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: healer-binding
subjects:
  - kind: ServiceAccount
    name: healer-sa
roleRef:
  kind: Role
  name: healer-role
  apiGroup: rbac.authorization.k8s.io