name: AIOps CI/CD Pipeline

on:
  push:
    branches: ["main"]
env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:

  test-and-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: |
           python -m pip install --upgrade pip
           python -m pip install -r requirements-dev.txt
           python -m pip install -r services/app_service/requirements.txt
           python -m pip list

      - name: Run Tests
        run: |
          PYTHONPATH=. python -m pytest services/

      #  Trivy FS Scan
      - name: Build Docker Image for Scan
        run: |
          docker build -t test-app ./services/app_service

      - name: Run Trivy Scan on Image
        uses: aquasecurity/trivy-action@v0.19.0
        with:
          image-ref: test-app
          severity: CRITICAL
          exit-code: 1

      #  SonarQube Scan
      - name: Sonar Scan
        uses: sonarsource/sonarqube-scan-action@v2
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

  docker-build-push:
    needs: test-and-scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build & Push APP SERVICE
      - name: Build App Service
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/app_service:latest ./services/app_service

      - name: Push App Service
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/app_service:latest

      #  Build & Push ML SERVICE
      - name: Build ML Service
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/ml_service:latest ./services/ml_service

      - name: Push ML Service
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/ml_service:latest